### ISSUE TITLE
Theme selection doesn't work if site is not at server root

### ISSUE THREAD

**Issue by justinfenn** [Worble/Zulma#9]
The theme switcher can't get alternative css files if the site exists at some path other than `/`.  If it's at `https://example.com/my/site`, for example, then theme selection won't work.  But it seems fine if it's `https://example.com/` instead.

**Comment by Worble** [comment]
Should be fixed by #10, although I don't have an easy way to test this though so let me know if it worked.

On another note regarding the theme switcher, I was so preoccupied wondering whether it _could_ be done I didn't consider whether it _should_, it's honestly not a great user experience if they do swap themes since it creates a white flash on every page load. In the future if I get time to rewrite some things, it'd probably be far better just to have one light and one dark theme and support [`prefers-color-scheme`](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme) instead.

**Comment by justinfenn** [comment]
Thanks @Worble, that change did fix the issue I was seeing.  FWIW, I do see the white flash on the first page load after switching themes, but after that it seems to go away.
